#!/bin/bash
echo OPENLitespeed FASTcgi Pagespeed memcached
hostname roninsmm.com
apt-get update -y 
apt-get upgrade -y
apt-get install build-essential python3 python3-acme python3-certbot python3-mock python3-openssl python3-pkg-resources python3-pyparsing python3-zope.interface rcs libpcre3-dev libexpat1-dev libssl-dev libgeoip-dev libudns-dev zlib1g-dev libxml2 libxml2-dev libpng-dev openssl ca-certificates apt-transport-https lsb-release software-properties-common dirmngr -y
wget -O - http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh | bash
apt-get update -y 
apt-get upgrade -y
apt-get install openlitespeed
apt-get install ols-pagespeed
echo "deb http://deb.debian.org/debian stretch-backports main contrib non-free" >> /etc/apt/sources.list
echo "deb-src http://deb.debian.org/debian stretch-backports main contrib non-free" >> /etc/apt/sources.list
apt-get update -y 
sudo apt install python-certbot-nginx -t stretch-backports
/usr/local/lsws/bin/lswsctrl start
apt-get update -y 
apt-get upgrade -y
apt-get install lsphp73 php-cgi  php-fpm php-apcu  php-apcu-bc
ln -sf /usr/local/lsws/lsphp73/bin/lsphp /usr/local/lsws/fcgi-bin/lsphp5
sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 100M/g' /usr/local/lsws/lsphp73/etc/php/7.3/litespeed/php.ini
sed -i 's/memory_limit = 128M/memory_limit = 256M/g' /usr/local/lsws/lsphp73/etc/php/7.3/litespeed/php.ini
sed -i 's/post_max_size = 8M/post_max_size = 100M/g' /usr/local/lsws/lsphp73/etc/php/7.3/litespeed/php.ini
sed -i 's/max_execution_time = 30/max_execution_time = 300/g' /usr/local/lsws/lsphp73/etc/php/7.3/litespeed/php.ini
apt-get update && apt-get upgrade -y
apt install mariadb-server -y
mysql_secure_installation
apt-get install fail2ban -y
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
echo "ignoreip = 127.0.0.1/8 139.162.211.218" >> /etc/fail2ban/jail.local
/usr/local/lsws/bin/lswsctrl status
/usr/local/lsws/admin/misc/admpass.sh
ufw default deny incoming
ufw default allow outgoing
ufw allow http && ufw allow https && ufw allow 8088/tcp && ufw allow 7080/tcp
ufw allow ssh
ufw enable && ufw reload && ufw status
service php-fpm restart
service nginx restart
echo http://139.162.211.218:8088 
echo http://139.162.211.218:7080 
