#!/bin/bash
hostnamectl set-hostname office.ondigitalseo.com
apt update && apt upgrade -y
apt install apache2 -y
sudo systemctl enable apache2.service
apt-get install mariadb-server mariadb-client
sudo systemctl enable mariadb.service
mysql_secure_installation
mysql -uroot <<MYSQL_SCRIPT
CREATE DATABASE Znae8Ucr;
CREATE USER '68o0A3ml'@'localhost' IDENTIFIED BY '225B6ClN';
GRANT ALL PRIVILEGES ON Znae8Ucr.* TO '68o0A3ml'@'localhost';
FLUSH PRIVILEGES;
MYSQL_SCRIPT
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ondrej/php
apt update
apt install zip unzip
apt install php7.1 libapache2-mod-php7.1 php7.1-pdo-mysql php7.1-common php7.1-curl php7.1-intl php7.1-mbstring php7.1-mcrypt php7.1-json php7.1-xmlrpc php7.1-soap php7.1-mysql php7.1-gd php7.1-xml php7.1-cli php7.1-zip
systemctl restart apache2.service
add-apt-repository ppa:certbot/certbot
apt update && apt upgrade
apt install certbot
systemctl restart apache2.service
certbot --apache -d office.ondigitalseo.com
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
apt install curl git
curl --silent --location https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt install nodejs
cd /var/www/html/
sudo git clone -b 2.4 https://github.com/oroinc/crm-application.git orocrm
cd orocrm
sudo composer install --prefer-dist --no-dev
php app/console oro:install --env=prod
